/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LifeInCertciaRouteImport } from './routes/life-in-certcia'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClassroomRouteImport } from './routes/classroom'
import { Route as CertificationHallRouteImport } from './routes/certification-hall'
import { Route as AiLabRouteImport } from './routes/ai-lab'
import { Route as AiHallRouteImport } from './routes/ai-hall'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearningIndexRouteImport } from './routes/learning.index'
import { Route as LearningPathwayIdRouteImport } from './routes/learning.$pathwayId'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeInCertciaRoute = LifeInCertciaRouteImport.update({
  id: '/life-in-certcia',
  path: '/life-in-certcia',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomRoute = ClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationHallRoute = CertificationHallRouteImport.update({
  id: '/certification-hall',
  path: '/certification-hall',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLabRoute = AiLabRouteImport.update({
  id: '/ai-lab',
  path: '/ai-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHallRoute = AiHallRouteImport.update({
  id: '/ai-hall',
  path: '/ai-hall',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathwayIdRoute = LearningPathwayIdRouteImport.update({
  id: '/learning/$pathwayId',
  path: '/learning/$pathwayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-hall': typeof AiHallRoute
  '/ai-lab': typeof AiLabRoute
  '/certification-hall': typeof CertificationHallRoute
  '/classroom': typeof ClassroomRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/life-in-certcia': typeof LifeInCertciaRoute
  '/news': typeof NewsRoute
  '/learning/$pathwayId': typeof LearningPathwayIdRoute
  '/learning/': typeof LearningIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-hall': typeof AiHallRoute
  '/ai-lab': typeof AiLabRoute
  '/certification-hall': typeof CertificationHallRoute
  '/classroom': typeof ClassroomRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/life-in-certcia': typeof LifeInCertciaRoute
  '/news': typeof NewsRoute
  '/learning/$pathwayId': typeof LearningPathwayIdRoute
  '/learning': typeof LearningIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-hall': typeof AiHallRoute
  '/ai-lab': typeof AiLabRoute
  '/certification-hall': typeof CertificationHallRoute
  '/classroom': typeof ClassroomRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/life-in-certcia': typeof LifeInCertciaRoute
  '/news': typeof NewsRoute
  '/learning/$pathwayId': typeof LearningPathwayIdRoute
  '/learning/': typeof LearningIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-hall'
    | '/ai-lab'
    | '/certification-hall'
    | '/classroom'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/faqs'
    | '/life-in-certcia'
    | '/news'
    | '/learning/$pathwayId'
    | '/learning/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-hall'
    | '/ai-lab'
    | '/certification-hall'
    | '/classroom'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/faqs'
    | '/life-in-certcia'
    | '/news'
    | '/learning/$pathwayId'
    | '/learning'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-hall'
    | '/ai-lab'
    | '/certification-hall'
    | '/classroom'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/faqs'
    | '/life-in-certcia'
    | '/news'
    | '/learning/$pathwayId'
    | '/learning/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiHallRoute: typeof AiHallRoute
  AiLabRoute: typeof AiLabRoute
  CertificationHallRoute: typeof CertificationHallRoute
  ClassroomRoute: typeof ClassroomRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  FaqsRoute: typeof FaqsRoute
  LifeInCertciaRoute: typeof LifeInCertciaRoute
  NewsRoute: typeof NewsRoute
  LearningPathwayIdRoute: typeof LearningPathwayIdRoute
  LearningIndexRoute: typeof LearningIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-in-certcia': {
      id: '/life-in-certcia'
      path: '/life-in-certcia'
      fullPath: '/life-in-certcia'
      preLoaderRoute: typeof LifeInCertciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom': {
      id: '/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof ClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification-hall': {
      id: '/certification-hall'
      path: '/certification-hall'
      fullPath: '/certification-hall'
      preLoaderRoute: typeof CertificationHallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lab': {
      id: '/ai-lab'
      path: '/ai-lab'
      fullPath: '/ai-lab'
      preLoaderRoute: typeof AiLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-hall': {
      id: '/ai-hall'
      path: '/ai-hall'
      fullPath: '/ai-hall'
      preLoaderRoute: typeof AiHallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$pathwayId': {
      id: '/learning/$pathwayId'
      path: '/learning/$pathwayId'
      fullPath: '/learning/$pathwayId'
      preLoaderRoute: typeof LearningPathwayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiHallRoute: AiHallRoute,
  AiLabRoute: AiLabRoute,
  CertificationHallRoute: CertificationHallRoute,
  ClassroomRoute: ClassroomRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  FaqsRoute: FaqsRoute,
  LifeInCertciaRoute: LifeInCertciaRoute,
  NewsRoute: NewsRoute,
  LearningPathwayIdRoute: LearningPathwayIdRoute,
  LearningIndexRoute: LearningIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
